name: Build
on:
  - push
  - pull_request

jobs:
  build:
    name: 'Build on ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}'

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - windows-2019
          - macOS-11
        python-version:
          - 3.9.13

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up python
        uses: actions/setup-python@v3
        if: runner.os != 'MacOS'
      - name: Set up python
        run: ./setup-osx.sh
        if: runner.os == 'MacOS'
      - name: Build SQLCipher
        if: runner.os == 'Windows'
        run: ./build.ps1
      - name: Build SQLCipher
        if: runner.os == 'Linux'
        run: ./build.sh
      - name: Build python package
        work_directory: ./pysqlcipher3
        run: python3 -m pip install --upgrade build && python -m build
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: pysqlcipher3/dist