name: Build
on:
  - push
  - pull_request

jobs:
  build:
    name: 'Build on ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}'

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
#           - windows-2019
#           - macOS-11
        python-version:
          - 3.9.13

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
        if: runner.os != 'MacOS'
      - name: Set up python
        run: ./setup-osx.sh
        if: runner.os == 'MacOS'
      - name: Build SQLCipher
        if: runner.os == 'Windows'
        run: ./build.ps1
      - name: Build SQLCipher
        if: runner.os == 'Linux'
        run: ./build.sh
      - name: Build sdist
        working-directory: /tmp/pybuild/pysqlcipher3/
        run: python3 -m pip install --upgrade build && python -m build -s
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.6.0
      - name: Build wheels
        working-directory: /tmp/pybuild/pysqlcipher3/
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: cp39-macosx_universal2 cp39-win_amd64 cp39-manylinux_x86_64 cp39-musllinux_x86_64 cp39-manylinux_aarch64 cp39-musllinux_aarch64
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl